### ISSUE TITLE
No new followers

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#100]
<del>Not positive, but I thought that there was a persistent note for all of your new followers for each of your  sites. Maybe I just haven't gotten a new follower in a long time?</del>

Also, there's been a report that follower notifications are broken and are not being received in any of the delivery methods, even though they are all checked in settings.

![screen shot 2017-05-15 at 10 28 14 am](https://cloud.githubusercontent.com/assets/618551/26065347/38b314e8-3959-11e7-9dbb-a77b2cdeef67.png)

**Comment by dmsnell** [comment]
> a persistent note for all of your new followers for each of your sites

not to my knowledge but it's an idea we could entertain

> follower notifications are broken

I'm pretty sure they aren't generally broken, but maybe there are certain cases they aren't coming through

**Comment by drw158** [comment]
Hm, I'm pretty there was one note per site that accumulated all of your followers. I could be wrong about it being persistent.

**Comment by dmsnell** [comment]
@drw158 new follower notifications _replace_ the old one if it's there but if, say, we get 100 comments on a post, those comment notifications would wipe out the follow notification

**Comment by drw158** [comment]
I can confirm that follow notifications work in general. I suppose we need to investigate this particular user's case.

**Comment by drw158** [comment]
Possibly related to the issue, my follower email notification is being marked as spam by wpcom 

<img width="321" alt="screen shot 2017-05-15 at 11 10 16 am" src="https://cloud.githubusercontent.com/assets/618551/26067424/d8962b98-395f-11e7-93af-1be161767ff8.png">

**Comment by dmsnell** [comment]
Closing for lack of more information and lack of corroborating reproduction. If we see this more we can reopen.
