### ISSUE TITLE
Unread items disappear once you click on them while the unread filter is selected

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#103]
> The big one is that “unread” is basically broken, when you click things they disappear, which loses the relationship between the item and the detail view, and also breaks keyboard navigation

Screenshot of problem:

![screen shot 2017-05-15 at 11 02 34 am](https://cloud.githubusercontent.com/assets/618551/26066906/0f727240-395e-11e7-8eea-12faeb62e752.png)

To reproduce:

- receive a notification
- click on Unread filter
- click on an unread item
- you'll see something similar to the above, where the item is no longer there, but the detail view is still present

Before, I think we had some sort of mechanism for keeping the item visible until the user changed filters.

**Comment by drw158** [comment]
I can confirm that the keyboard navigation is sort of broken. To reproduce:

- receive a notification
- click on Unread filter
- use your down arrow key to select the first unread note
- notice that the blue border is visible
- the detail view does not change
- notice that once you click on the note with your mouse, the detail view updates correctly 

![screen shot 2017-05-15 at 11 14 12 am](https://cloud.githubusercontent.com/assets/618551/26067378/a71c4e80-395f-11e7-8278-e4e52c27b843.png)

**Comment by roundhill** [comment]
I'll try and tackle this one.

**Comment by drw158** [comment]
Can confirm this is a regression. Check out the `notifications` widget url and you can see that it works there, but not in `notificationsbeta`.

**Comment by roundhill** [comment]
Fixed via #121
