### ISSUE TITLE
Add a way to go to your notification settings from the panel

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#104]
There could be an easier, more direct way to access the notification settings.

One idea from Dan:

> Maybe a settings icon could go in the first time group header on the right? Lots of space there

**Comment by roundhill** [comment]
Doesn't look too bad :)

<img width="410" alt="screen shot 2017-05-17 at 4 16 36 pm" src="https://cloud.githubusercontent.com/assets/789137/26180106/40b25324-3b1c-11e7-9bec-5223d02c29ad.png">

**Comment by dmsnell** [comment]
Resolved by #108
