### ISSUE TITLE
Calypso: Vertically centered views look off

### ISSUE THREAD

**Issue by roundhill** [Automattic/notifications-panel#113]
The calculations for centering things vertically aren't working as well in Calypso, as they seem to be off by the height of the master bar:

<img width="410" alt="screen shot 2017-05-24 at 9 37 22 am" src="https://cloud.githubusercontent.com/assets/789137/26415051/ffd190f0-4065-11e7-8093-aa74c9ce03eb.png">

We'll need to be careful at fixing this so that it looks good in both standalone and in Calypso. Maybe we're using the height of the window, and should use the main div's height instead.

**Comment by kwight** [comment]
Reopening; #115 introduced some scroll and background color issues.
