### ISSUE TITLE
`Read` state not syncing to multiple browser tabs

### ISSUE THREAD

**Issue by roundhill** [Automattic/notifications-panel#130]
**To reproduce**
1. Open two new calypso tabs with the notifications panel open.
2. Mark a notification as read in one tab.
3. Switch to the other tab, and observe that the notification is still unread.

Note: Changing tabs in the second tab appears to update the unread state, so maybe we just need to force a `render()`?

cc @dmsnell for any thoughts.

**Comment by dmsnell** [comment]
@roundhill this can probably be resolved by doing something in the same place you updated the `filteredUnreads`. The tab-sync works via `localStorage` and storage events and was a bit wonky. Now that we have a much better system to handle this we should iterate on the design.

For now, I think we might just need to add a condition for `note_read_status` events in `rest-client#handleStorageEvent()` to update a local note copy. I'll take a look at this…

**Comment by roundhill** [comment]
> For now, I think we might just need to add a condition for note_read_status events in rest-client#handleStorageEvent() to update a local note copy (because right now we don't respond to those storage changes until the next render as you discovered). I'll take a look at this…

Thanks for taking a look. If we could get an 'easy' fix out first that'd be good.
