### ISSUE TITLE
Pixel jump on filter buttons

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#131]
In the iframe (frontend), the filter buttons jump when you open the detail view (by clicking on any notification).

Safari Version 10.1.1 
Mac OS 10.12.5

![note bug](https://cloud.githubusercontent.com/assets/618551/26798045/cab63f72-49f4-11e7-8f33-80520c0db6c6.gif)

**Comment by roundhill** [comment]
This is weird because @Copons added a left border which caused this shift which I fixed by adding 1px of padding when the border was gone, but I don't see the border in your screenshot... it looks like an older version of notifications-panel to me.
