### ISSUE TITLE
Iframe RTL: note animation is incorrect

### ISSUE THREAD

**Issue by gwwar** [Automattic/notifications-panel#143]
In RTL languages the notifications panel is on the left side instead of the right. This means that the animation should be left to right, rather than a right to left slide in.

To reproduce:

1. In your Jetpack site navigate to /wp-admin/options-general.php
2. Set your language to a RTL language 
3. Refresh the main page and open notifications
4. Click on a note to expand

**Comment by kwight** [comment]
Animations are correct now, left to right.
