### ISSUE TITLE
React.createClass is deprecated and will be removed in React v16.

### ISSUE THREAD

**Issue by kwight** [Automattic/notifications-panel#154]
> Warning: Localized(BackButton): React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

Instances to be updated:

 - [x] ActionButton
 - [x] ActionsPane
 - [x] BlockComment
 - [x] BlockPost
 - [ ] BlockUser
 - [x] ButtonApprove
 - [x] ButtonLike
 - [x] ButtonSpam
 - [x] ButtonTrash
 - [ ] CommentReplyInput
 - [x] ContainerHotkey
 - [x] EmptyMessage
 - [x] Error
 - [x] FilterBar
 - [ ] FollowLink
 - [ ] Gridicons
 - [x] ImageLoader
 - [ ] Layout
 - [x] NavButton
 - [ ] NoteBody
 - [ ] NoteList
 - [x] Preface
 - [ ] StatusBar
 - [ ] Suggestion
 - [ ] SummaryInList
 - [ ] SummaryInSingle
 - [ ] UndoListItem
 - [ ] UserHeader

**Comment by abhishek-2102** [comment]
Read this [#8854](https://github.com/facebook/react/issues/8854) 
You may get some idea about the warning.

**Comment by kwight** [comment]
Closed in the above PRs. There is still some usage of `create-react-class` though.
