### ISSUE TITLE
Iframe left border is missing on narrow widths.

### ISSUE THREAD

**Issue by kwight** [Automattic/notifications-panel#155]
On narrow widths where the detailed view doesn't pop out, but rather replaces the main list, the left border is missing:

![screen shot 2017-06-12 at 9 18 03 am](https://user-images.githubusercontent.com/349751/27043846-5c9b0840-4f50-11e7-8568-a6a126c6ba44.png)

**Comment by roundhill** [comment]
This was fixed via #158. It will go full width at <= 480px
