### ISSUE TITLE
Notifications sometimes don't appear when user is proxied.

### ISSUE THREAD

**Issue by kwight** [Automattic/notifications-panel#162]
We have some reports of proxied users not having their notifications displayed upon opening the panel. Refreshing, visiting another site and coming back, or reconnecting the proxy seem to "fix" it.

**Comment by kwight** [comment]
cc/ @designsimply

**Comment by dmsnell** [comment]
I've heard reports of it also not loading outside of the proxy, in mobile, by @hannahswain if I remember properly.

**Comment by dmsnell** [comment]
It's also my suspicion that something funny is happening here with the initial load state. We try not to poll for notes if the panel isn't visible, but maybe it think's it's hidden when it shows and gets lost.

Alternatively, if it has trouble connecting to PingHub in the right sequence of events, maybe it things that PingHub is established and we don't need to poll, having skipped the initial poll.

**Comment by hannahswain** [comment]
I've been seeing this intermittently on mobile and haven't seen a pattern as to when it happens.  

Setup: 
* Android Nexus 5x, version 7.1.2
* Chrome
* When opening WordPress.com links from Slack app (stripped down version of Chrome?)
* No proxy, just WIFI or data connection

This issue doesn't come up when using the WordPress app.

**Comment by karenalma** [comment]
This has been happening to me pretty consistently over at least the last week. As @kwight said, refreshing or reloading the page fixes it.

**Comment by eurello** [comment]
I've been having this problem very consistently in Chrome lately -- but not just while proxied. I am also having this problem on my personal computer where I'm not proxied.

**Comment by lettergrade** [comment]
I have been having this problem very consistently in Firefox while proxied.

**Comment by kwight** [comment]
Is anyone able to reliably reproduce this issue? I know I've experienced it myself a few times, but haven't seen nor been able to reproduce it at all in the last week or so. :/

**Comment by eurello** [comment]
I just this second updated Chrome and that seems to have fixed it for me... Previously, it was happening constantly on two different computers (one proxied, one not).

**Comment by kwight** [comment]
Interesting, I also upgraded Chrome some days ago (buuuuuuut have also been emptying app data for testing).

**Comment by iamgabrielma** [comment]
I've been having this problem the last week or two, when I realized something was being funny about the notifications, I'd added some details and screenshots [here](https://lannisterp2.wordpress.com/2017/07/04/been-experiencing-some-problems-with-the-reader-notifications/#comment-205).

Plot twist: I got a "new" notification from March 2017 on July 2017.

I normally use Firefox, will try to test with other browsers / debug further.

**Comment by dmsnell** [comment]
All, could you try to confirm a behavior I have found?

If I load a page with the tab open and visible the notifications load.
If I load a page in the background (another tab is selected the tab is just hidden) the notifications don't load.

cc: @hannahswain @kwight @karenalma @lettergrade @eurello @iamgabrielma

**Comment by eurello** [comment]
Yes, @dmsnell I was just able to reproduce what you describe, even with my newly updated Chrome.

**Comment by kwight** [comment]
I've been unable to replicate myself, using these steps:

1. Enter WordPress.com in a tab's URL address bar.
2. Hit Enter, and switch tabs right away.
3. Wait a minute, go back to the tab when the spinner is done.

I've also tried hitting reload and switching tabs quickly, then going back. Browser-wise, this has been on Chrome (up-to-date, proxied and unproxied; also out-of-date, unproxied on a personal comp; with devtools open and closed).

**Comment by dmsnell** [comment]
This should hopefully be fixed now with the deploy of #167. For now it's only in the beta channel.
