### ISSUE TITLE
Do we have a reason for our UPPERCASE styling?

### ISSUE THREAD

**Issue by kwight** [Automattic/notifications-panel#169]
Looking at https://github.com/Automattic/notifications-panel/blob/master/src/templates/image-loader.jsx#L9

Do we want to use SCREAMING_SNAKE_CASE for constants?

Any reason for the keys and values being uppercase?

**Comment by dmsnell** [comment]
Only because they are constants and this makes it obvious. They were brought over from other code originally but the stye didn't conflict. See the way we use our Redux actions for related use.
