### ISSUE TITLE
Mentions: Enter key doesn't work for active @mention

### ISSUE THREAD

**Issue by beaulebens** [Automattic/notifications-panel#170]
When in the notifications panel, and replying to a comment, you can "@mention" someone else on that site. In other places (e.g. the Calypso Editor) you can start typing a name after the `@` and then hit `Enter` to select the highlighted user. In the Notifications panel, that doesn't seem to work, and I think I am just getting the first name in the full list (not the filtered list even).

Example; start replying to a comment:
<img width="398" alt="screen_shot_2017-07-13_at_5_03_40_pm" src="https://user-images.githubusercontent.com/108942/28191434-81746fd4-67ed-11e7-8985-3248410ff46d.png">

See that the person you want to mention is highlighted, and hit enter to select them, and get someone else entirely (I believe the first person in the dataset driving the auto-complete):
<img width="394" alt="screen_shot_2017-07-13_at_5_04_06_pm" src="https://user-images.githubusercontent.com/108942/28191458-9c5247cc-67ed-11e7-9bb8-668c539137cb.png">

Note that the inserted user's username does not match the search query at all.

If you use the mouse to click the name instead, then it works as expected.

I'm on Chrome/macOS.

**Comment by kwight** [comment]
Fixed in #204 .
