### ISSUE TITLE
i18n: Top navigation bar loads in English, switches to correct language after first click

### ISSUE THREAD

**Issue by akirk** [Automattic/notifications-panel#173]
I have my UI language set to German, yet the header loads in English.

Here is a demo:
![notifications-translation](https://user-images.githubusercontent.com/203408/28924932-a435d090-7863-11e7-839b-55921c71095e.gif)

**Comment by dmsnell** [comment]
Oh interesting. It looks like it isn't changing until the app re-renders. Can you also try doing something like opening a notification or pressing a key to see if the behavior is the same?

We kind of _have_ to do the english-then-language load on account of how the app loads int translations. I think the only thing practically that we could do at this moment is try to prevent the app from rendering at all until languages load, but I'm not sure that's idea.

Thanks for reporting @akirk !

**Comment by akirk** [comment]
No, neither clicking on a notification, nor using keys fixes the translation, just switching to another filter.

![notifications-translation-rerender](https://user-images.githubusercontent.com/203408/28956684-8da556f8-78ee-11e7-92d7-98feb4ef29b5.gif)
