### ISSUE TITLE
i18n: Filter bar always shows "Unread" in English in Calypso

### ISSUE THREAD

**Issue by akirk** [Automattic/notifications-panel#176]
Might be related to #173 (though in Calypso not the whole filter bar is in English, like in that ticket) and might be fixed by #175 but I am unable to confirm this.

Examples:

German:
![screen shot 2017-08-03 at 17 23 05](https://user-images.githubusercontent.com/203408/28929603-acc6de86-7870-11e7-9d8c-40362464f0ac.png)

Italian:
![screen shot 2017-08-03 at 17 23 54](https://user-images.githubusercontent.com/203408/28929607-b2436302-7870-11e7-87cb-e6fed0b8a418.png)

**Comment by gwwar** [comment]
This should be closed by #175 but it looks like I can still see this in prod. Remaining tasks here are to  create another release for Calypso and the stand alone version.

**Comment by akirk** [comment]
@gwwar I don't know how this is deployed, I posed the question in #175. It seems to be just merged but undeployed.

**Comment by dmsnell** [comment]
Yeah we just need to version bump the notifications panel in Calypso

**Comment by gwwar** [comment]
Thanks @akirk I was triaging issues for @Automattic/lannister 

To get new versions of Notifications out we explicitly publish a new version of Notifications to [npm](https://www.npmjs.com/package/notifications-panel), and bump the [npm dependency](https://github.com/Automattic/wp-calypso/pull/13725) in Calypso. On the wpcom side, we svn commit the new version using [notifications-client](https://github.com/Automattic/notifications-client) to update resources.

**Comment by akirk** [comment]
Thanks for the explanation. Shall I do the deploying, given that I have merged #175?

**Comment by gwwar** [comment]
@akirk I can help walk you through the Calypso steps if you're interested 👍  If you're busy, Lannister will push out a new version pretty soon.

**Comment by kwight** [comment]
Our recent update took care of this:
<img width="434" alt="screen shot 2017-10-17 at 4 28 46 pm" src="https://user-images.githubusercontent.com/349751/31694326-814b030e-b358-11e7-9516-38eb6ae35b0b.png">
