### ISSUE TITLE
Author Role Can't Approve or Trash Comments From Notifications Panel

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/notifications-panel#180]
Authors can see comment notifications in the notifications panel, but trying to approve or trash a comment while logged in as an author does not work.

Instead of the comment actually deleting or being approved, it keeps its current status. If you refresh, you'll see the comment still hasn't been approved or deleted.

I've tried this from a user account and also from my own test account while not proxied. I needed to change the role from Author to Editor in order to be able to approve the comments from the notifications panel.

Via wp-admin, Authors can successfully approve or trash comments.

Here is a 41 second screencast where I try to repeatedly approve and trash a test comment on a user's site from an Author role:

https://cloudup.com/cOQIDeZO4mU

Issue reported in:
604018-hc
656108-zd

Discussed in Slack:
/archives/C02DQP0FP/p1503931928000041

**Comment by gwwar** [comment]
Note https://core.trac.wordpress.org/ticket/6907#comment:4

**Comment by kwight** [comment]
Fixed in r163946-wpcom and https://github.com/Automattic/jetpack/pull/7980 (part of v5.5, Nov 7, 2017 release).
