### ISSUE TITLE
Entities/characters don't show up correctly in site titles.

### ISSUE THREAD

**Issue by justinshreve** [Automattic/notifications-panel#190]
While testing my order notification (https://github.com/Automattic/wp-calypso/issues/16181), @timmyc saw one of his site titles (`i <3 brobee`) did not display properly. I tested with another notification and had the same issue:

<img width="347" alt="screen shot 2017-10-25 at 1 39 02 pm" src="https://user-images.githubusercontent.com/689165/32021986-e8ec0968-b989-11e7-855a-b6044b75dbb1.png">

<img width="388" alt="screen shot 2017-10-25 at 1 39 09 pm" src="https://user-images.githubusercontent.com/689165/32021994-ec0db75e-b989-11e7-9bcc-6de124b91162.png">

I tried passing the site title a couple different ways, but I think that it might be an issue here in the panel.

Related? https://github.com/Automattic/notifications-panel/issues/188

**Comment by kwight** [comment]
Looks like this is fine now:

<img width="520" alt="screen shot 2018-01-12 at 3 55 43 pm" src="https://user-images.githubusercontent.com/349751/34899981-24142f60-f7b1-11e7-9389-0ebcc4f86bfe.png">
