### ISSUE TITLE
Comments: add deep linking to Comments management

### ISSUE THREAD

**Issue by vindl** [Automattic/notifications-panel#195]
Most of the basic comment management can be done through notifications, but if you want to edit the comment slightly before approving it (e.g. correct typos and similar) you have to manually go to `wp-admin` or now the new Comments management section in Calypso.

It would be helpful if we could deep link directly to single Comment view in Calypso for quick editing and approval. It might also be useful to have something similar for post specific view.

**Comment by dmsnell** [comment]
<img width="395" alt="screen shot 2017-11-15 at 3 03 07 pm" src="https://user-images.githubusercontent.com/5431237/32857532-1ceccda0-ca16-11e7-91e3-3cfbf1406460.png">

how about another icon, maybe a cog here that could take us there? it would need to pass some new action, of course, like, `MANAGE_COMMENT` which we could intercept in Calypso but link in standalone mode.

nice recommendation!

**Comment by vindl** [comment]
> how about another icon, maybe a cog here that could take us there?

Sounds good if that's what we usually use in manage context. /cc @drw158

**Comment by drw158** [comment]
We should first add the Edit button to be consistent with the mobile apps. The Edit button would go to /comments.

As an added enhancement: Manage comments button


![artboard copy](https://user-images.githubusercontent.com/618551/32905875-e1d7bc88-cac0-11e7-8fdc-ef4d7845ba35.png)

or positioned at the bottom:
![artboard](https://user-images.githubusercontent.com/618551/32905879-e43fd74e-cac0-11e7-9a4b-f16e2fd7ff43.png)

**Comment by dmsnell** [comment]
nice mockups @drw158 - thanks!

on that note, and I see that the mobile apps already follow this pattern, but why is `Trash` so close to `Approved`? Would we have value in making the order `Liked / Approved / Edit / Trash / Spam` or something else to give more "fat-finger tolerance"?

**Comment by drw158** [comment]
I don't know... it's slightly different everywhere. In this case, it's been like that for a very long time :) 

Reader and /comments are different as well. It probably should be the same order as /comments, and whatever we do here needs to also match the apps.

**Comment by kwight** [comment]
This is what we seem to have ended up with in `/comments`:
![screen shot 2018-01-08 at 11 18 59 am](https://user-images.githubusercontent.com/349751/34688140-f293f78e-f465-11e7-9731-f4294865a7c3.png)

@drw158 what's your suggestion for next actions here?

**Comment by drw158** [comment]
My suggestion is to first add the Edit button to the Notifications panel. It would link to the edit action in /comments. Then, order the actions to be consistent with /comments (Approve, Spam, Trash, Like, Edit). This will at least get the actions consistent within Calypso. Then, make an issue for reordering the actions in the mobile apps.

**Comment by kwight** [comment]
> My suggestion is to first add the Edit button to the Notifications panel. It would link to the edit action in /comments.

This is in progress in #222 .
