### ISSUE TITLE
Updating notification preferences for mobile devices

### ISSUE THREAD

**Issue by wensco** [Automattic/notifications-panel#198]
I went to https://wordpress.com/me/notifications to remove email notifs from one of the p2s I follow and noticed that the mobile notifications list a specific mobile device. 

I got a new phone a couple days ago and it didn't occur to me that this would have any impact on notifications.

I noticed that all of the mobile notifications look like they are being sent to my old device (samsung s6, which was factory reset so the app should no longer be associated with that phone), yet I am receiving notifications on my new Pixel device. Below is an example of how my mobile notifications look for every blog I follow:

<img width="708" alt="notifications samsung" src="https://user-images.githubusercontent.com/7942966/33630136-48c3fe62-d9d4-11e7-8136-70093694236b.png">

I now have a dropdown where I can choose between the current Samsung and my new device, Pixel. 
http://d.pr/i/opzXGv

Based on the fact that I am getting notifications on the Pixel, I'm not sure that it's necessary to update the device listed in the drop down. If I do need to update, there is no way to globally edit all of the blogs I follow to use the new device. Perhaps we can either remove that dropdown if it's not necessary or allow users to globally update it.

**Comment by kwight** [comment]
Hi @wensco ! If I understand correctly, that dropdown allows you to have different settings per device, as opposed to selecting one device or the other; is that what you meant?

**Comment by wensco** [comment]
Hey there @kwight - thanks for looking into this. I'm just wondering why it's still showing my old device since it is no longer connected to the WordPress.com app and would like to know how I can remove it from being displayed in that dropdown. 

Also, if a device is removed, how does the app know what notifications to set for the new device if multiple devices can have different notification settings? I assumed when I factory reset the old phone and then added the app to my new phone that 1) the old device would no longer be connected to the app 2) notifications would no longer go to the old device 3) the new device would replace the old device and "inherit" the notification settings. 

But you know what they say about assuming... :)

**Comment by kwight** [comment]
Ah, now I understand; the old device shouldn't be in that dropdown because the app had been removed from it.

I think this is more of a Calypso bug rather than this repo (which is everything that happens within the notification panel); tracking here: https://github.com/Automattic/wp-calypso/issues/21344
