### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by roundhill** [Automattic/notifications-panel#22]
- [x] Back button arrow isn't centered
- [x] iOS scroll jank
- [x] CSS Reset Needed (just body margin:0)
- [x] Badges need centering:
<img width="373" alt="screen shot 2017-05-02 at 11 43 16 am" src="https://cloud.githubusercontent.com/assets/789137/25633703/e74d654e-2f2c-11e7-9b95-343d30551d23.png">

- [x] Weird icon for following:
<img width="184" alt="screen shot 2017-05-02 at 11 51 07 am" src="https://cloud.githubusercontent.com/assets/618551/25633968/d0a55c7e-2f2d-11e7-8f79-c721a4af931f.png">

- [x] Text is gray in the old client (this is actually a bug in the old client I think) #wont-fix
<img width="928" alt="screen shot 2017-05-02 at 12 03 24 pm" src="https://cloud.githubusercontent.com/assets/618551/25634418/68d36904-2f2f-11e7-9f10-12396a3dea64.png">

- [x] comment text is a different size (actually it was just a typeface difference):
<img width="1214" alt="screen shot 2017-05-02 at 12 48 12 pm" src="https://cloud.githubusercontent.com/assets/618551/25636326/f3c2d4ea-2f35-11e7-9812-98015a8de916.png">

- [x] Detail view needs min width of 400px
- [x] Empty state text has no style. (#36)

- [x] No unread notifications screen is unstyled

<img width="325" alt="screen shot 2017-05-03 at 9 45 31 am" src="https://cloud.githubusercontent.com/assets/1464705/25671599/76a80394-2fe5-11e7-8917-bf128296bedd.png">

**Comment by drw158** [comment]
For the badges

```
.single-view .badge img {
    display: block;
    margin: 0 auto;
    padding: 36px 16px 16px;
}
```

**Comment by drw158** [comment]
Weird icon content code:

```
.noticon-following:before {
    content: "\f803";
}
```

**Comment by drw158** [comment]
The empty notes styling:

```
#empty-notes {
    text-align: center;
    position: relative;
    top: 50%;
    padding: 0 32px;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
}
```

It's an id, so maybe it was copied over as a class?
