### ISSUE TITLE
Left/right arrow shortcuts should be reversed for single column.

### ISSUE THREAD

**Issue by kwight** [Automattic/notifications-panel#261]
Reported by @drw158 in https://github.com/Automattic/notifications-client/issues/523:

Right now, if the notifications panel is in single-column mode, the left arrow shortcut opens the notification and the right arrow goes back to the list. This should be reversed for single column, but remain the same on the two column layout.

**Comment by drw158** [comment]
My bad for not including screenshots. I'm not sure what I meant...I think the layout has changed since I opened the issue. We can close, because the arrows make sense now.
