### ISSUE TITLE
WPDesktop: Section headers are blank

### ISSUE THREAD

**Issue by astralbodies** [Automattic/notifications-panel#284]
It looks like the section headers are appearing as blank on wp-desktop 3.4.0-beta1 which uses v2.1.10 and wp-calypso frozen at `10686c554de82ee0defb7165ae7b234e9f36045b`.

![tomlq0](https://user-images.githubusercontent.com/373903/43099336-81317e38-8e87-11e8-8fd1-e0f50c6d460a.png)

You can download that version of the desktop app by visiting https://github.com/Automattic/wp-desktop/releases/tag/untagged-d3da0285dbc707ff1db9.

cc: @gwwar

**Comment by gwwar** [comment]
Ah, and I can't repro this using the beta DMG. 😅 Can a few other folks try this?

**Comment by adlk** [comment]
Fixed here: https://github.com/Automattic/notifications-panel/pull/285
