### ISSUE TITLE
Gap between Notifications panel and Masterbar

### ISSUE THREAD

**Issue by vindl** [Automattic/notifications-panel#54]
There is a very small gap between Notifications panel and Masterbar, and underlying content can be seen through it.

![gap](https://cloud.githubusercontent.com/assets/1182160/25685755/78fffb68-301e-11e7-8a29-3e6fe79c2687.png)

**Comment by Copons** [comment]
Is this still a thing? I can't see it

**Comment by vindl** [comment]
Yup, I still see it.

**Comment by vindl** [comment]
It's weird because masterbar has a `height: 46px`, and notificaiton panel is positioned with `top: 46px` so it should work fine. It works fine in Firefox for me, but I can still see it in Chrome. 
Reproduced on: Ubuntu 16.04 LTS, Chrome Version 57.0.2987.133 (64-bit).

**Comment by dmsnell** [comment]
As of now I am not seeing this and I'm pretty sure we fixed it. Please reopen @vindl if you are still minding the gap.
