### ISSUE TITLE
Infinite Scroll trigger point

### ISSUE THREAD

**Issue by apeatling** [Automattic/notifications-panel#62]
If the infinite scroll trigger point was two notes before the end of the list, the whole thing would feel a lot faster to load. You'd be waiting a lot less time for the next page to load when using it under normal scrolling conditions. Also, if using the keyboard shortcuts do the same if you select two notes before the end.

**Comment by dmsnell** [comment]
Updated in #64 - now it triggers around four notes from the bottom
