### ISSUE TITLE
Filter bar overlapping left side of panel in Edge browser

### ISSUE THREAD

**Issue by apeatling** [Automattic/notifications-panel#68]
<img width="213" alt="screen shot 2017-05-04 at 10 56 01 am" src="https://cloud.githubusercontent.com/assets/1464705/25717856/ba8fe170-30b8-11e7-9c11-8d82e1c8fe13.png">

**Comment by Copons** [comment]
On Chrome too actually.
It's a border missing on `.wpnc__filter`, not an overlap.
