### ISSUE TITLE
Iframe: Panel automatically opens after page load

### ISSUE THREAD

**Issue by Copons** [Automattic/notifications-panel#72]
When loading a page on a Jetpack site, after a couple of seconds the panel slides in automatically.

![may-04-2017 11-45-08](https://cloud.githubusercontent.com/assets/2070010/25719743/50103ece-30bf-11e7-842e-85b407b7dd1a.gif)

**Comment by roundhill** [comment]
I noticed this too!

**Comment by dmsnell** [comment]
This probably relates to sending the `togglePanel` message.

**Comment by dmsnell** [comment]
Closing because it was resolved in some PR I can't find. If I'm wrong @copons then please reopen. Since we have been running this for a while now and haven't received an insane amount of support requests I will consider it resolved.
