### ISSUE TITLE
Unexpected left shadow on list when detail is open

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#81]
<img width="206" alt="screen shot 2017-05-04 at 3 51 10 pm" src="https://cloud.githubusercontent.com/assets/618551/25728056/949e6490-30e1-11e7-978d-ccb626fecac1.png">

**Comment by Copons** [comment]
Can't see it in staging
<img width="77" alt="screen shot 2017-05-05 at 09 18 03" src="https://cloud.githubusercontent.com/assets/2070010/25754379/c89da746-3173-11e7-9395-7b9988bc25c7.png">

**Comment by drw158** [comment]
I don't see it anymore
