### ISSUE TITLE
Likes detail view doesn’t tell you when the likes happened

### ISSUE THREAD

**Issue by drw158** [Automattic/notifications-panel#99]
![screen shot 2017-05-15 at 11 06 17 am](https://cloud.githubusercontent.com/assets/618551/26067068/8c0b0e5c-395e-11e7-89b3-76b8ea5a77d3.png)

**Comment by drw158** [comment]
This was intentional when we first designed it. I personally don't think it's an issue.

**Comment by roundhill** [comment]
Hmm seems like information most users won't care about, but if it wouldn't hurt anything to add it somewhere I don't see why not. I checked the likes table and we are indeed storing a timestamp there so we at least have the data available to us.

**Comment by kwight** [comment]
Closing; someone can reopen if they feel strongly about it.
